FROM python:3.10.9-alpine3.17 as builder

WORKDIR usr/app/web

COPY . .

COPY requirements.txt .
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /usr/src/app/wheels -r requirements.txt

RUN pip install colorama
RUN pip install art