# Generated by Django 5.0.6 on 2024-06-07 13:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Наименование департамента')),
            ],
        ),
        migrations.CreateModel(
            name='EsUser',
            fields=[
                ('unique_number', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный номер')),
                ('username', models.CharField(max_length=30, verbose_name='Ник')),
                ('password', models.CharField(default='D2472Ct4uq', max_length=10, unique=True, verbose_name='Пароль')),
                ('computer_info', models.FileField(upload_to='users/information/computer/', verbose_name='Информация о компьютере')),
                ('ip_address', models.GenericIPAddressField(blank=True, editable=False, null=True, verbose_name='IP-адрес')),
                ('country_and_region', models.CharField(blank=True, max_length=120, null=True, verbose_name='Страна и регион')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_select_departament', to='auth_user.departament', verbose_name='Отдел')),
            ],
        ),
    ]
