# Generated by Django 5.0.6 on 2024-06-07 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esuser',
            name='departament',
        ),
        migrations.AddField(
            model_name='departament',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_select_departament', to='auth_user.esuser', verbose_name='Отдел'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='esuser',
            name='password',
            field=models.CharField(default='Fbw9JciDfr', max_length=10, unique=True, verbose_name='Пароль'),
        ),
    ]
