# Generated by Django 5.0.6 on 2024-06-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_remove_esuser_departament_departament_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esuser',
            name='computer_info',
            field=models.FileField(blank=True, null=True, upload_to='users/information/computer/', verbose_name='Информация о компьютере'),
        ),
        migrations.AlterField(
            model_name='esuser',
            name='password',
            field=models.CharField(max_length=10, unique=True, verbose_name='Пароль'),
        ),
    ]
