FROM python:3.12-alpine3.17 as bot-builder

WORKDIR usr/app/bot

COPY . .

COPY requirements.txt .
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /usr/src/app/bot/wheels/ -r requirements.txt

RUN pip install django
RUN pip install art